function [Electrode,SE,Time_spike,Spike_startes,Spike_stops] = importfile(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [Electrode,SE,Time_spike,Spike_startes,Spike_stops] = IMPORTFILE(FILE)
%   reads data from the first worksheet in the Microsoft Excel spreadsheet
%   file named FILE and returns the data as column vectors.
%
%   [Electrode,SE,Time_spike,Spike_startes,Spike_stops] =
%   IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   [Electrode,SE,Time_spike,Spike_startes,Spike_stops] =
%   IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   [Electrode,SE,Time_spike,Spike_startes,Spike_stops] = importfile('Spikes_locations1.xlsx','Sheet1',4,13);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/11/17 16:55:48

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 4;
    endRow = 13;
end

%% Import the data
data = xlsread(workbookFile, sheetName, sprintf('A%d:E%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    tmpDataBlock = xlsread(workbookFile, sheetName, sprintf('A%d:E%d',startRow(block),endRow(block)));
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

%% Allocate imported array to column variable names
Electrode = data(:,1);
SE = data(:,2);
Time_spike = data(:,3);
Spike_startes = data(:,4);
Spike_stops = data(:,5);

